development:
  adapter: postgresql
  encoding: unicode
  database: tic_tac_toe_development
  host: localhost
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: tic_tac_toe_test
  host: localhost
  pool: 5
  username: postgres
  password: password
